baseURL = 'https://chao-surprisemotherfucker-yi.github.io/hugoV0/'
canonifyURLs = true
relativeURLs = true
title = 'My New Hugo Site'
theme = 'relearn'

[markup]
  [markup.highlight]
    # line numbers in a table layout will shift if code is wrapping, so better
    # use inline; besides that visually both layouts have the same look and behavior
    lineNumbersInTable = false
    lineNos = true

    # if `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT Mermaid and Math codefences will not work anymore! So this is a
    # mandatory setting for your site if you want to use Mermaid or Math codefences
    guessSyntax = false

    # the shipped variants come with their own modified chroma syntax highlightning
    # style which is imported in theme-relearn-light.css, theme-relearn-dark.css, etc.;
    # if you want to use a predefined style instead:
    # - remove `noClasses` or set `noClasses = true`
    # - set `style` to a predefined style name
    noClasses = false
    # style = "tango"

   

[outputs]

home = [ "HTML", "RSS", "SEARCH"]

[params]

  editURL = "http://localhost"
  themeVariant = ["relearn-light", "relearn-dark"]
  additionalContentLanguage = [ "en", "es", "fr"]


    [[menu.shortcuts]]
    name = "Lenguaje PHP"
    URL = "http://php.net"
    weight = "10"

    [[menu.shortcuts]]
    name = "Google"
    URL = "http://google.es"
    weight = "20"


  [params.logo]

    path = "/Logo_of_Twitter.png"

  



defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = true


[languages]


  [languages.es]

    title = "Español"
    languageName = "Español"
    weight = 1
    contentDir= "content/es"
    disabled = false
    languageCode = 'es'

    [languages.es.params]
    landingPageName = "<i class='fas fa-home'></i> Casa Haha"


  [languages.en]
  
    title = "English"
    languageName = "English"
    weight = 2
    contentDir= "content/en"
    disabled = false
    languageCode = 'en-us'

   [languages.en.params]
    landingPageName = "<i class='fas fa-home'></i> Home Sweet Home"


  [languages.fr]
  
    title = "Francaise"
    languageName = "Francaise"
    weight = 3
    contentDir= "content/fr"
    disabled = false
    languageCode = 'fr'
    
    [languages.fr.params]
    landingPageName = "<i class='fas fa-home'></i> Au revoir"
    


